### ISSUE TITLE
The subtitle search provides irrelevant results

### ISSUE THREAD

**Issue by tsiktsiris** [wako-unofficial-addons/helios#9]
Video name is not passed correctly to the subtitle addons. 

I am using OpenMeta with Elementum .

**Comment by davidreedmichigan** [comment]
If you use OpenMeta then you don't use Helios, cause Helios is sending the link directly on Kodi without use of any add-on. 
For your issue, the problem is that with Kodi I didn't find via their API, how to send video metadata. Hence Kodi doesn't know what is playing... What we have thought is to be able to copy/paste the video name in wako remote prompt. Still one more step but it's the simplest we've found

**Comment by davidreedmichigan** [comment]
wako add this copy/paste option. I'm closing this
